name = input("Write your first name: ")
lname = input("Write your last name: ")

print(name.lower(),lname.lower())
print(name.upper(),lname.upper())
print(name.islower(),lname.isupper())
print(name.startswith("S"),lname.startswith("B"))
print(" ".join(name))
print(name.split("a",2))
print(name.rjust(10),"is my name")
print(name.ljust(10),"is my name")
print(name.center(10),"is my name")
print(name.lstrip('saks'))
print(name.rstrip('ham'))
print(name[::-1])